#!/bin/bash

STEP=5

[[ "$1" == "Up" || "$1" == "+" ]] && d="-A $STEP"
[[ "$1" == "Down" || "$1" == "-" ]] && d="-U $STEP"

brillo -s intel_backlight -u 150000 -q $d

b=$(brillo -G)
Left=${b%%"."*}

# Show the brightness notification
msgId="991159"
dunstify -a "changeBrightness" -u low -i display-brightness-high-symbolic -r "$msgId" \
-h int:value:$Left "Brightness: ${Left}%"