#!/bin/bash

STEP=2
b=$(brillo -G)
Left=${b%%"."*}
if [[ $Left -lt 10 ]]; then
	$(brillo -S 11)
	echo "Brightness set too low: $Left"
	exit 1
fi
[[ "$1" == "Up" || "$1" == "+" ]] && d="-A $STEP"
[[ "$1" == "Down" || "$1" == "-" ]] && d="-U $STEP"

brillo -s intel_backlight -q $d

# Show the brightness notification
msgId="991159"
dunstify -a "changeBrightness" -u low -i display-brightness-high-symbolic -r "$msgId" \
-h int:value:$Left "Brightness: ${Left}%"