#!/bin/bash

MON=$(xrandr --current| grep "eDP.* connected" | awk '{print $1}')	# Discover monitor name with: xrandr | grep " connected"
STEP=5			# Step Up/Down brightnes by: 5 = ".05", 10 = ".10", etc.
MINBRIGHTNESS=10
if ! [[ "$1" == "Up" || "$1" == "+" || "$1" == "Down" ||  "$1" == "-" ]]
	then
	if ! [[ "$1" =~ ^[0-9]+$ ]]
		then
			echo "Sorry integers only"
			exit 1
	fi
	if ! [[ $1 -ge 0 && $1 -le 100 ]]
		then
			echo "Brightness must be between 0 and 100"
			exit 1
	fi
	MathBright=$1
else
	CurrBright=$( xrandr --verbose --current | grep ^"$MON" -A5 | tail -n1 )
	CurrBright="${CurrBright##* }"	# Get brightness level with decimal place

	Left=${CurrBright%%"."*}		# Extract left of decimal point
	Right=${CurrBright#*"."}		# Extract right of decimal point
	
	MathBright="0"
	[[ "$Left" != 0 ]] && MathBright="$Left"00			# 1.0 becomes "100"
	[[ "${#Right}" -eq 1 ]] && Right="$Right"0			# 0.5 becomes "50"
	[[ "${#Right}" -eq 3 ]] && Right=${Right:0:2}		# 0.050 becomes "05"
	MathBright=$(( MathBright + Right ))
	echo $MathBright

	[[ "$1" == "Up" || "$1" == "+" ]] && MathBright=$(( MathBright + STEP ))
	[[ "$1" == "Down" || "$1" == "-" ]] && MathBright=$(( MathBright - STEP ))
fi

[[ "${MathBright:0:1}" == "-" ]] && MathBright=0						# Negative not allowed
[[ "$MathBright" -gt 100  ]] && MathBright=100							# Can't go over 1
[[ "$MathBright" -le $MINBRIGHTNESS ]] && MathBright=$MINBRIGHTNESS		# Can't go below MINBRIGHTNESS
[[ "$MathBright" -lt 10 ]] && MathBright=0$MathBright					# Can't go below STEP


# #Capture brightness parcent before its padded
dispBrightness=$MathBright

if [[ "$MathBright" -eq 100 ]] ; then
	CurrBright=1
else
	MathBright="$MathBright"000		# Pad with lots of zeros
	CurrBright=".${MathBright:0:2}"
fi
xrandr --output "$MON" --brightness "$CurrBright"	# Set new brightness

# Show the brightness notification
msgId="991159"
dunstify -a "changeBrightness" -u low -i display-brightness-high-symbolic -r "$msgId" \
-h int:value:$dispBrightness "Brightness: ${dispBrightness}%"