#!/bin/sh
xrandr --output DP1 --off
xrandr --output DP2 --off
xrandr --output DP3 --off
xrandr --output VIRTUAL1 --off
xrandr --output DP1-2 --crtc 1 --mode 3840x2160 --pos 0x0       --rate 30.00 --rotate right
xrandr --output DP1-1 --crtc 0 --mode 3840x2160 --pos 2160x1680 --rate 30.00 --primary
xrandr --output eDP1  --crtc 2 --mode 3840x2160 --pos 6000x1680 --rate 60.00

~/.fehbg


